library(quantmod)
library(forecast)
from.dat <- as.Date("01/01/08",format="%m/%d/%y")
to.dat <- as.Date("12/31/13",format="%m/%d/%y")
getSymbols("VNM",src="google",from=from.dat,to=to.dat)
head(VNM)
mVNM <- to.monthly(VNM)
vnmOpen <- Op(mVNM)
ts1 <- ts(vnmOpen,frequency=12)
plot(ts1,xlab="Years+1",ylab="VNM")
plot(decompose(ts1),xlabs="Years+1")

ts1Train <- window(ts1,start=1,end=5)
ts1Test <- window(ts1,start=5,end=c(7-.01))
plot(ts1Train)
lines(ma(ts1Train,order=3),col="red")
  
ets1 <- ets(ts1Train,model="MMM")
fcast <- forecast(ets1)
plot(fcast); lines(ts1Test,col="red")
accuracy(fcast,ts1Test)
